### ISSUE TITLE
Vulkan does not properly synchronize with OpenGL in X-Plane 11.50

### ISSUE THREAD

**Issue by JT8D-17** [GPUOpen-Drivers/AMDVLK#179]
### Issue

When running X-Plane in Vulkan mode with AMDVLK, any plugin drawing in OpenGL space exhibits rendering artifacts.

[Example screenshot](https://drive.google.com/file/d/1RFVCN1AQnksQUpZTloSt81MScSN3ln8q/view)

&nbsp;

### Information:

AMD 3700X
Arch Linux with Kernel 5.8.2
Xserver 1.20.8-3

AMD 5700XT (Navi10)
AMDVLK 2020.Q3.3
Mesa 20.1.6 (for OpenGL)

X-Plane 11.50r1
X-Plane launch options: VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json ./X-Plane-x86_64 --vulkan
[X-Plane log](https://drive.google.com/file/d/1DBO8ayr8d72ACUgtsorh6ZXgPc1sjbDR/view?usp=sharing)

[Renderdoc capture](https://drive.google.com/file/d/1NxFd6z9-mGwTolVNZy12bTmWXVw8Wvyn/view?usp=sharing)

&nbsp;

### Reproduction:

1. Download and install the X-Plane demo from [the official site](https://www.x-plane.com/desktop/try-it/) (requires around 10 GB of free disk space)
2. Update the demo by running the installer again, checking the "Check for new betas..." box. This is crucial in switching to the 11.50 codepath that includes Vulkan mode!
3. X-Plane can be directly launched in Vulkan mode from the terminal with the "--vulkan" switch. Might be worth running it once to check if everything is in order. Make sure to quit XP before going on.
4. Obtain the latest DataRefTool release [from GitHub](https://github.com/leecbaker/datareftool/releases/tag/2020.03.24)
5. The archive needs to be unzipped twice. The resulting folder needs to be moved into "/X-Plane 11/Resources/plugins". The resulting path to the plugin file should be "/X-Plane 11/Resources/plugins/DataRefTool_2020_03_23/lin.xpl".
6. Start X-Plane in Vulkan mode, start a flight at Seattle (KSEA), one of the demo areas, and access DatarefTool from the menubar at the top ("Plugins" --> "DataRefTool" --> "View Datarefs")
7. The result should be what you see in the example picture above.

&nbsp;

### Notes:

- This bug affects any plugin that tries to draw in 2D space via OpenGL and not just DataRefTool.
- The "other" open source Vulkan driver for Linux is also affected.
- As far as I remember, this issue does not occur in Windows (it's been a while since I've tested it).
- Can't test the sync behavior of AMDGPU Pro since it breaks KDE 5 for me.
- The developer of X-Plane is aware of this issue, but says it needs to be fixed/worked around on the driver side.
- GPUs from a major competitor are neither affected by this on Windows or Linux.

&nbsp;

Hope that's enough information for a start. Tell me if you need more.

**Comment by qiaojbao** [comment]
The root cause is the imported image for plugin render, its creation option's default values have some difference with Mesa's.
We will fix it.

**Comment by JT8D-17** [comment]
Thank you!

Let me know if you need more information.

**Comment by JaxLinAMD** [comment]
@JT8D-17 issue fixed in v-2020.Q4.6

**Comment by JT8D-17** [comment]
The situation is now better, but some plugins still do not synchronize properly.

See [Avitab](https://github.com/fpw/avitabl) (freeware) with [vFlyteAir's Navion](https://forums.x-plane.org/index.php?/files/file/48223-vflyteair-ryan-navion-205-vintage-freeware/) (freeware, butr requires registration to download):

![AMDVLK](https://user-images.githubusercontent.com/36554499/102557573-d15cf100-40cb-11eb-8c81-6834ee792cb2.jpg)

For comparison, this is in X-Plane's OpenGL mode (provided by Mesa):

![Nav_OGL](https://user-images.githubusercontent.com/36554499/102557630-f18cb000-40cb-11eb-8f18-f190bf234e06.jpg)

This is with the [ToLiSS Airbus A321](https://store.x-plane.org/Airbus-A321-by-Toliss_p_1174.html) (payware):

![AMDVLK_A321](https://user-images.githubusercontent.com/36554499/102557892-81caf500-40cc-11eb-9b3c-26d337fcdf4e.jpg)

Again, for comparison, OpenGL mode provided by Mesa)::

![A321_OGL](https://user-images.githubusercontent.com/36554499/102557927-95765b80-40cc-11eb-89c8-8263b82d2a3d.jpg)


I think this is a texture coordinate space issue.

[X-Plane log for the Navion with AMDVLK](https://github.com/GPUOpen-Drivers/AMDVLK/files/5712781/Log_AMDVLK.txt)

[Terminal output for the Navion with AMDVLK](https://github.com/GPUOpen-Drivers/AMDVLK/files/5712797/Z_X-Plane_Terminal_AMDVLK.log)


[X-Plane log for the A321 with AMDVLK](https://github.com/GPUOpen-Drivers/AMDVLK/files/5712790/Log.txt)

[Terminal output for the A321 with AMDVLK](https://github.com/GPUOpen-Drivers/AMDVLK/files/5712801/Z_X-Plane_Terminal_A321.log)


I sadly can not provide a Renderdoc capture, because as of release 11.51b3, X-Plane blocks AMDVLK and the "--force_run" argument does not work from Renderdoc (but it does when launched from a terminal). See my Renderdoc launch options:

![image](https://user-images.githubusercontent.com/36554499/102558834-a3c57700-40ce-11eb-86a3-1608b9730f60.png)

[X-Plane log from a failed launch](https://github.com/GPUOpen-Drivers/AMDVLK/files/5712836/Log.txt)

For comparison, a working launch:
> VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json "$PWD/X-Plane-x86_64" --vulkan --force_run


I have informed Laminar Research, X-Plane's developer, about this and tried to argue in favor of the Mesa+AMDVLK combination, but despite an e-mail exchange, I did not receive feedback whether future X-Plane versions will fix this.

All I have in terms of Renderdoc captures is those I made for Mesa's Vulkan driver, [which seems to suffer from the same issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3895#note_712199).

**Comment by qiaojbao** [comment]
I had reproduced this new issue on Navi10.
And it works well on Vega20.
I will try to find out the root cause and the difference between Vega20 and Navi10.

**Comment by qiaojbao** [comment]
Hi JT8D-17,
The root cause is OGL not handle the image mipLevels info correctly while import external memory.
AMD pro driver also has this issue too.
The AMD pro driver stack will be fixed firstly.

About the Mesa OGL and Mesa RADV, the iPad seems be black. I guess there will be a lot of work to do for Mesa OGL + RADV, and for Mesa OGL + AMDVLK.

**Comment by Gfurst** [comment]
Hi all, I don't know if its been mentioned before, but there also seems to be an error with the terrain radar mod, that adds functioning terrain radars to some compatible aircraft, namely the default Boeing 737-800 from Laminar. It just doesn't show up, silently fails without any clue to the logs.
Also, I still keep getting some issues, with python graphical elements flashing (fse ui, xsquackbox, text boxes and such).

**Comment by JT8D-17** [comment]
Thanks for looking into this @qiaojbao!

@Gfurst Could be the same bug.

**Comment by dechilders** [comment]
@jinjianrong I see this was closed (I've been watching it for a while because this affects my system), but I am still seeing this bug. If this has supposedly been fixed, then do I need to open a new issue? I'm currently on AMDVLK 2021.Q1.4-1 from Arch (says last updated 02/25/2021).

**Comment by jinjianrong** [comment]
Just realized the issue needs a fix in opengl which has not been included in latest AMDGPU Pro release.  Reopen the issue

**Comment by Gfurst** [comment]
Was this fixed for the open-source driver though? I haven't noticed it so far

**Comment by jinjianrong** [comment]
The fix is only for  Linux Pro OGL + AMDVLK.  Still needs a fix in MesaGL to get MesaGL + AMDVLK working.

**Comment by JT8D-17** [comment]
Does the fix involve [VK_PROVOKING_VERTEX_MODE_FIRST_VERTEX_EXT](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkProvokingVertexModeEXT)?

**Comment by ICSimulations** [comment]
Hello. I was wondering if the AMD driver will be updated to stop the flashing with X-plane and amd 6900xt cards. This happens with certain plugins.

**Comment by qiaojbao** [comment]
@ICSimulations, this issue was only fixed in AMD Linux Pro OGL + AMDVLK, if you run into some similar issues under the latest AMD pro driver stack, could you list the plugins and AMD Linux pro driver version here, please?

**Comment by ICSimulations** [comment]
> @ICSimulations, this issue was only fixed in AMD Linux Pro OGL + AMDVLK, if you run into some similar issues under the latest AMD pro driver stack, could you list the plugins and AMD Linux pro driver version here, please?

Ahh..sorry, this was under windows. Should I try the AMD Pro driver? Happy to try that against with the plugins causing the flickering.

**Comment by jinjianrong** [comment]
@ICSimulations,  yes,  please help try AMD Linux Pro driver. thanks

**Comment by ICSimulations** [comment]
I am on windows.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JT8D-17** [comment]
> I am on windows.

Then neither this **Linux-only driver** nor this issue tracker is for you.

**Comment by qiaojbao** [comment]
Verified xplane-11 with the latest 2024Q3.1 and Mesa 24.0.9-0ubuntu0.1, no corruption observed.
AviTab-0.3.21.zip
AviTab-0.6.3.zip
datareftool_2020_03_24.zip
DataRefTool_2021_07_14.zip
